import { SITE_URL } from '@/lib/site';
import { sitemapIds } from '@/components/portal/sitemap-data';

export const revalidate = 3600;

/** Sitemap index (Phase 14): points at the chunked child sitemaps generated by `app/sitemap.ts`. */
export async function GET() {
  const ids = await sitemapIds();
  const lastmod = new Date().toISOString();
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ids.map((id) => `  <sitemap><loc>${SITE_URL}/sitemaps/${id}.xml</loc><lastmod>${lastmod}</lastmod></sitemap>`).join('\n')}
</sitemapindex>
`;
  return new Response(body, { headers: { 'content-type': 'application/xml; charset=utf-8', 'cache-control': 'public, max-age=3600' } });
}
