/** Georgian notification templates. Keys are stable identifiers used across modules. */
export type TemplateVars = Record<string, string | number | undefined>;

export const TEMPLATES: Record<string, { title: (v: TemplateVars) => string; body: (v: TemplateVars) => string }> = {
  listing_alert: { title: () => 'ახალი ფართი თქვენი ძებნით', body: (v) => `„${v.search}“ — ${v.title}, ${v.price}` },
  liveness_request: { title: () => 'ფართი ისევ თავისუფალია?', body: (v) => `„${v.title}“ — დაადასტურეთ ერთი დაჭერით: ${v.link}` },
  liveness_hidden: { title: () => 'განცხადება დამალდა', body: (v) => `„${v.title}“ 72 საათში არ დადასტურდა და დამალდა. დაადასტურეთ, რომ ისევ გამოჩნდეს.` },
  listing_approved: { title: () => 'განცხადება გამოქვეყნდა', body: (v) => `„${v.title}“ ხელმისაწვდომია ძებნაში.` },
  listing_rejected: { title: () => 'განცხადება უარყოფილია', body: (v) => `„${v.title}“: ${v.reason}` },
  verification_approved: { title: () => 'მესაკუთრე ვერიფიცირებულია', body: (v) => `„${v.title}“ — მიენიჭა ვერიფიცირებული მესაკუთრის ნიშანი.` },
  verification_rejected: { title: () => 'ვერიფიკაცია უარყოფილია', body: (v) => `„${v.title}“: ${v.reason}` },
  offer_received: { title: () => 'ახალი შეთავაზება', body: (v) => `„${v.title}“ — ${v.price}, ${v.term} თვე` },
  offer_countered: { title: () => 'კონტრ-შეთავაზება', body: (v) => `„${v.title}“ — ${v.price}, ${v.term} თვე` },
  offer_accepted: { title: () => 'შეთავაზება მიღებულია', body: (v) => `„${v.title}“ — ხელშეკრულების პროექტი მზად არის.` },
  offer_rejected: { title: () => 'შეთავაზება უარყოფილია', body: (v) => `„${v.title}“` },
  viewing_booked: { title: () => 'ჩვენება ჯავშნილია', body: (v) => `„${v.title}“ — ${v.when}` },
  viewing_reminder: { title: () => 'ჩვენება ხვალ', body: (v) => `„${v.title}“ — ${v.when}` },
  message_new: { title: (v) => `ახალი შეტყობინება: ${v.from}`, body: (v) => String(v.body ?? '') },
  demand_match: { title: () => 'თქვენი მოთხოვნასთვის შესაფერისი ფართი', body: (v) => `${v.title}, ${v.price}` },
  demand_contact: { title: () => 'თქვენ მოთხოვნაზე გამოეხმაურნენ', body: (v) => `${v.from}: ${v.body}` },
  prebooking: { title: () => 'ახალი წინასწარი ჯავშნა', body: (v) => `„${v.title}“ — ${v.from}` },
  service_quote: { title: () => 'ახალი ფასის შეთავაზება', body: (v) => `${v.provider}: ${v.price}` },
  service_request: { title: () => 'ახალი მოთხოვნა მომსახურებაზე', body: (v) => `${v.category}: ${v.body}` },
  crm_match: { title: () => 'CRM: ახალი ფართი კლიენტისთვის', body: (v) => `${v.contact} — ${v.title}` },
  crm_task_due: { title: () => 'CRM: დავალების ვადა', body: (v) => `${v.title} — ${v.when}` },
  owner_report: { title: () => 'კვირის რეპორტი', body: (v) => `„${v.title}“: ${v.views} ნახვა, ${v.reveals} ზარი, ${v.viewings} ჩვენება` },
  payment_succeeded: { title: () => 'გადახდა მიღებულია', body: (v) => `${v.what} — ${v.amount}` },
  payment_failed: { title: () => 'გადახდა ვერ შესრულდა', body: (v) => `${v.what} — ${v.amount}. სცადეთ ხელახლა.` },
  subscription_grace: { title: () => 'გამოწერის ვადა გადაცილებულია', body: (v) => `${v.plan}: გადაიხადეთ ${v.until}-მდე` },
  rent_due: { title: () => 'იჯარის გადახდის ვადა', body: (v) => `${v.period}: ${v.amount}, ვადა ${v.due}` },
  rent_late: { title: () => 'იჯარა ვადაგადაცილებულია', body: (v) => `${v.period}: ${v.amount} + ჯარიმა ${v.penalty}` },
  maintenance_update: { title: () => 'მოთხოვნის სტატუსი შეიცვალა', body: (v) => `${v.title}: ${v.status}` },
  escrow_update: { title: () => 'დეპოზიტის სტატუსი', body: (v) => `${v.status}` },
  generic: { title: (v) => String(v.title ?? 'lokacia.ge'), body: (v) => String(v.body ?? '') },
};
