import type { ListingCard } from '@lokacia/contracts';

/** Neutral "architectural drawing" placeholder (BRAND.md forbids stock photos). */
export function drawingPhoto(seed = 1, w = 640, h = 480): string {
  const x = 80 + (seed * 37) % 120;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#E3E8E1"/><g stroke="#8A968F" stroke-width="1" fill="none"><rect x="${x}" y="60" width="${w - x * 2}" height="${h - 140}"/><line x1="${x}" y1="${h / 2}" x2="${w - x}" y2="${h / 2}"/><line x1="${w / 2}" y1="60" x2="${w / 2}" y2="${h - 80}"/></g><circle cx="${w - x - 24}" cy="84" r="8" fill="#D8A31A"/></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const BUSINESS_TYPES: Record<string, string> = {
  cafe: 'კაფე',
  restaurant: 'რესტორანი',
  office: 'ოფისი',
  retail: 'მაღაზია',
  warehouse: 'საწყობი',
  pharmacy: 'აფთიაქი',
  beauty: 'სილამაზის სალონი',
};

export const businessTypeName = (slug: string) => BUSINESS_TYPES[slug] ?? slug;

export const listings: ListingCard[] = [
  {
    id: '0192f1a0-0000-7000-8000-000000000001',
    slug: 'vake-chavchavadze-kafe-64',
    title: 'ფართი კაფესთვის ჭავჭავაძის პროსპექტზე, პირველი ხაზი',
    dealType: 'rent',
    status: 'active',
    businessTypes: ['cafe', 'restaurant'],
    priceMinor: 450_000,
    currency: 'GEL',
    pricePeriod: 'month',
    areaM2: 64,
    floor: 1,
    address: 'ი. ჭავჭავაძის პრ. 37',
    districtName: 'ვაკე',
    districtSlug: 'vake',
    lat: 41.7094,
    lng: 44.7671,
    isOwner: true,
    verifiedOwner: true,
    commissionPct: null,
    lastConfirmedAt: daysAgo(3),
    publishedAt: daysAgo(12),
    vip: true,
    offPlan: false,
    completionDate: null,
    cover: drawingPhoto(1),
    photosCount: 12,
    locationScore: 82,
    passport: { widthM: 8, depthM: 8, ceilingM: 3.4, powerKw: 25 },
  },
  {
    id: '0192f1a0-0000-7000-8000-000000000002',
    slug: 'saburtalo-office-140',
    title: 'ოფისი ბიზნეს-ცენტრში, საბურთალო',
    dealType: 'rent',
    status: 'active',
    businessTypes: ['office'],
    priceMinor: 980_000,
    currency: 'GEL',
    pricePeriod: 'month',
    areaM2: 140,
    floor: 7,
    address: 'ალ. ყაზბეგის პრ. 24',
    districtName: 'საბურთალო',
    districtSlug: 'saburtalo',
    lat: 41.7241,
    lng: 44.7536,
    isOwner: false,
    verifiedOwner: false,
    commissionPct: 50,
    lastConfirmedAt: daysAgo(1),
    publishedAt: daysAgo(30),
    vip: false,
    offPlan: false,
    completionDate: null,
    cover: drawingPhoto(2),
    photosCount: 8,
    locationScore: 74,
    passport: { widthM: 10, depthM: 14, ceilingM: 3, powerKw: 15 },
  },
  {
    id: '0192f1a0-0000-7000-8000-000000000003',
    slug: 'didube-warehouse-620',
    title: 'საწყობი რამპით და 6 მ ჭერით, დიდუბე',
    dealType: 'sale',
    status: 'active',
    businessTypes: ['warehouse'],
    priceMinor: 112_000_000,
    currency: 'GEL',
    pricePeriod: 'total',
    areaM2: 620,
    floor: 1,
    address: 'ც. დადიანის ქ. 211',
    districtName: 'დიდუბე',
    districtSlug: 'didube',
    lat: 41.7468,
    lng: 44.7797,
    isOwner: true,
    verifiedOwner: false,
    commissionPct: null,
    lastConfirmedAt: null,
    publishedAt: daysAgo(4),
    vip: false,
    offPlan: false,
    completionDate: null,
    cover: null,
    photosCount: 0,
    locationScore: null,
    passport: { widthM: 20, depthM: 31, ceilingM: 6, powerKw: 80 },
  },
  {
    id: '0192f1a0-0000-7000-8000-000000000004',
    slug: 'isani-offplan-retail-95',
    title: 'კომერციული ფართი მშენებლე კომპლექსში',
    dealType: 'transfer',
    status: 'active',
    businessTypes: ['retail', 'pharmacy'],
    priceMinor: 6_500_000,
    currency: 'GEL',
    pricePeriod: 'total',
    areaM2: 95.5,
    floor: 1,
    address: 'ქეთევან დედოფლის პრ. 4',
    districtName: 'ისანი',
    districtSlug: 'isani',
    lat: 41.6921,
    lng: 44.8211,
    isOwner: false,
    verifiedOwner: false,
    commissionPct: 3,
    lastConfirmedAt: daysAgo(9),
    publishedAt: daysAgo(40),
    vip: false,
    offPlan: true,
    completionDate: '2027-06-30',
    cover: drawingPhoto(4),
    photosCount: 5,
    locationScore: 61,
    passport: { widthM: null, depthM: null, ceilingM: 4.2, powerKw: null },
  },
];
